### ISSUE TITLE
[TASK] Resolve dependencies with security vulnerabilities in GitHub

### ISSUE THREAD

**Issue by MagdalenaLarge** [ONSdigital/design-team#211]
We received alert from the GitHub that our Repository has vulnerable dependencies.

They are listed under this [link](https://github.com/ONSdigital/design-system/security/dependabot).

We need to address the issues and resolved them.

**Comment by precious-onyenaucheya-ons** [comment]
Axios Update Blockers:

wait-on: This is a transitive dependency of jest-dev-server, which is used by jest-environment-puppeteer within jest-puppeteer. Since jest-dev-server hasn’t updated wait-on, upgrading Axios is currently blocked.

ws and cookie Update Blockers:

browser-sync: This dependency relies on socket.io, which is used by ws. However, browser-sync has not updated socket.io to the latest version (4.8.1), preventing us from updating ws until this dependency is updated.
